---
- name: Add MongoDB Repo
  copy:
    src: mongodb-org.repo
    dest: /etc/yum.repos.d/mongodb-org.repo
- name: Import MongoDB GPG Key
  rpm_key:
    state: present
    key: https://www.mongodb.org/static/pgp/server-3.4.asc
- name: Install MongoDB
  yum: name=mongodb-org state=latest
- name: start and enable jenkins
  systemd:
    name: mongod
    state: started
    enabled: True
