# ansible-playbook -i "localhost," -c local dev-env.yaml
#
# Tested on CentOS7, Ubuntu 16.04
---
- hosts: all
  tasks: 
    - include_role:
        name: git
      vars:
        git_user_email: 'jay.stockhausen@gmail.com'
        git_user_name: 'Jay Stockhausen'
    - include_role:
        name: vim
      vars:
        vim_plugins: ['stockhausenj/emmet-vim', 'stockhausenj/vim-javascript', 'stockhausenj/vim-pug']
