# ansible-playbook -i hosts go-dev.yml --become --become-method=sudo
---
- hosts: go
  tasks:
  - name: Install Go
    unarchive:
      url: https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz
      dest: /usr/local/go
    become: yes
  - name: Create projects Directory
    file: path=$HOME/projects state=directory
    with_nested:
      - ['projects', 'bin']
      - ['projects', 'src']
      - ['projects', 'pkg']
  - name: Update PATH Environment Variable
    lineinfile:
      path: $HOME/.bash_profile
      regexp: '^PATH='
      line: 'PATH=$PATH:$HOME/.local/bin:$HOME/bin:/usr/local/go/bin'
  - name: Add GOBIN Environment Variable
    lineinfile:
      path: $HOME/.bash_profile
      regexp: '^export GOBIN'
      line: 'export GOBIN="$HOME/projects/bin"'
  - name: Add GOPATH Environment Variable
    lineinfile:
      path: $HOME/.bash_profile
      regexp: '^export GOPATH'
      line: 'export GOPATH="$HOME/projects/src"'
  - name: Load bash_profile
    shell: source $HOME/.bash_profile
