---
- name: Install nodejs and npm
  when: ansible_distribution == "CentOS"
  shell: curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash - && yum -y install nodejs
  become: yes
- name: Install nodejs and npm
  when: ansible_distribution == "Ubuntu"
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && apt install -y nodejs
  become: yes
