---
- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 755
  become: true
- name: Add kubectl Alias and Bash Completion to .bashrc
  lineinfile:
    dest: $HOME/.bashrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
  - { regexp: '^source <(kubectl completion bash)', line: 'source <(kubectl completion bash)' }
  - { regexp: '^alias k=kubectl', line: 'alias k=kubectl' }
  - { regexp: '^complete -F __start_kubectl k', line: 'complete -F __start_kubectl k' }
