---
- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ version }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 755
  become: true
- name: Create kube dir
  file:
    path: $HOME/.kube
    state: directory
    mode: '0755'
- name: Copy kube-ps1 script to kube dir
  copy:
    src: kube-ps1.sh
    dest: /usr/bin/kube-ps1.sh
    mode: '0755'
  become: true
- name: Copy kubectx script to path
  copy:
    src: kubectx
    dest: /usr/bin/kubectx
    owner: root
    group: root
    mode: '0755'
  become: true
- name: Copy kubens script to path
  copy:
    src: kubens
    dest: /usr/bin/kubens
    owner: root
    group: root
    mode: '0755'
  become: true
