- name: Install tmux plugin manager (TPM)
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: $HOME/.tmux/plugins/tpm
- name: Copy tmux conf file
  copy:
    src: tmux.conf
    dest: $HOME/.tmux.conf
- name: Install tmux
  apt:
    name: tmux
  become: true
